openapi: 3.0.1
info:
  title: API Cotizador de Seguro Vehicular
  version: 1.0.0
  description: >
    Esta API permite calcular una cotización de seguro vehicular 
    basado en información del vehículo y del conductor.  
    **Todos los endpoints requieren autenticación con JWT**.

servers:
  - url: http://localhost:8080
    description: Servidor local

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      tags:
        - Autenticación
      summary: Inicia sesión y obtiene un JWT
      description: Devuelve un token JWT válido para acceder a los demás endpoints.
      parameters:
        - name: username
          in: query
          required: true
          description: Nombre de usuario
          schema:
            type: string
      responses:
        '200':
          description: Token generado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Token JWT generado
              example:
                token: eyJhbGciOiJIUzI1NiJ9...

  /customers/cotizaciones:
    post:
      tags:
        - Cotizaciones
      summary: Cotiza un seguro vehicular
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CotizacionRequest'
            example:
              marca: Audi
              modelo: A4
              anio: 2018
              tipoUso: carga
              edadConductor: 40
      responses:
        '200':
          description: Cotización generada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDtoCotizacion'
              example:
                data:
                  primaBase: 500
                  ajustes:
                    - "Año > 2015 (+15%)"
                    - "Uso: carga (+10%)"
                    - "Marca Audi (+10%)"
                  primaTotal: 675.00
                message: Cotización generada con éxito
                status: SUCCESS
        '401':
          description: No autorizado (token JWT requerido)
        '500':
          description: Error interno del servidor

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CotizacionRequest:
      type: object
      required:
        - marca
        - modelo
        - anio
        - tipoUso
        - edadConductor
      properties:
        marca:
          type: string
        modelo:
          type: string
        anio:
          type: integer
        tipoUso:
          type: string
        edadConductor:
          type: integer

    CotizacionResponse:
      type: object
      properties:
        primaBase:
          type: number
          format: double
        ajustes:
          type: array
          items:
            type: string
        primaTotal:
          type: number
          format: double

    ResponseDtoCotizacion:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CotizacionResponse'
        message:
          type: string
        status:
          type: string