version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: insurance_postgres
    restart: always
    environment:
      POSTGRES_DB: vehicle_insurance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: insurance_redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: insurance_app
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/vehicle_insurance
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: 1234
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      APP_JWT_SECRET: claveSuperSecreta123
      APP_JWT_EXPIRATION: 3600
    command: ["java", "-jar", "app.jar"]
    volumes:
      - ./target/insurance-quote-1.0.0.jar:/app.jar

volumes:
  postgres_data:
